### ISSUE TITLE
General Documentation

### ISSUE THREAD

**Issue by finnbar** [codebndr/compiler#13]
This is probably a stupid question, but how do you make a successful request to the compiler? I'm having difficulty understanding what data the server actually wants to receive and there are no tutorials explaining how this works. I've been using xmlhttp to post the sketch to the server, but I only get fail messages despite the fact that I'm only using a simple ' void setup(){} void loop(){} ' script.

Thanks in advance!

**Comment by tzikis** [comment]
Hey finnbar, did you check the Wiki?
In the API page (https://github.com/codebendercc/compiler/wiki/Compiler-API), you'll find a curl command to test the request.

**Comment by finnbar** [comment]
Ah, I knew I'd forgotten to check something! Thank you very much, that solves everything!

**Comment by weiway** [comment]
Sorry I have to comment on a closed issue. 

I've followed the installation steps on the compiler wiki for 4 times. 
Every time it seems to be installed correctly and apache2 service is running, but request to the route "complier/status" returns a 404.
I also tried other example requests in the wiki, but all returns a 404.
I'm using Ubuntu14.04 on AWS EC2.
Please help, Thank you!
