### ISSUE TITLE
can not post using python

### ISSUE THREAD

**Issue by macomzzl** [codebndr/compiler#53]
If I use python to post data to this compiler server api, it returns "invalid input".
I use urllib2 to post. And I found that the request data the server received is not  a json.

**Comment by tzikis** [comment]
Hey @macomzzl does the CURL example work for you? It's hard to know how to help you without knowing exactly the request you're sending

**Comment by macomzzl** [comment]
@tzikis the CURL example is ok for me. But my application uses python to write. So I want to use python to post data to the compiler server.
Here is my test using python. And it doesn't work.

```
import urllib
import urllib2

json_data = {
                     'files':[{"content": "void setup()\n{\n  pinMode(0, OUTPUT);\n}\n\nvoid loop()\n{\n  digitalWrite(0,HIGH);\n\n}", "filename": "Arduino.ino"}],
                     'libraries':[], #key:[]
                     'format':"hex",
                     'version':'105',
                     'build':{
                        'mcu':'atmega328p',
                        'f_cpu':'16000000L',
                        'core':'arduino',
                        'variant':'standard'
                        }

                    }

url="http://the_url_of_your_compiler/authorizationKey/API_Version"
req = urllib2.Request(url)
print urllib.urlencode(json_data)
req.add_data(urllib.urlencode(json_data))
resp = urllib2.urlopen(req)

print resp.read()
```

**Comment by tzikis** [comment]
I'm afraid I can't help since I don't know much about python. You'll need to find a way to see what kind of HTTP message your python script creates, vs the HTTP message the cURL command creates

I'll have to close this issue, since it isn't related to the project itself
